!!python/object:huggingface_hub.community.DiscussionWithDetails
author: VeronicaBatista
conflicting_files: null
created_at: 2023-07-31 11:02:40+00:00
diff: null
endpoint: https://huggingface.co
events:
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: /avatars/0733253aca866003a59a7d7a38672af6.svg
      fullname: Veronica Batista
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: VeronicaBatista
      type: user
    createdAt: '2023-07-31T12:02:40.000Z'
    data:
      edited: false
      editors:
      - VeronicaBatista
      hidden: false
      identifiedLanguage:
        language: en
        probability: 0.47390496730804443
      isReport: false
      latest:
        author:
          avatarUrl: /avatars/0733253aca866003a59a7d7a38672af6.svg
          fullname: Veronica Batista
          isHf: false
          isPro: false
          name: VeronicaBatista
          type: user
        html: '<p>Hello, I tried to import this model and got an error:</p>

          <p>model_path = r''openllmplayground/openalpaca_3b_600bt_preview''<br>tokenizer
          = LlamaTokenizer.from_pretrained(model_path)</p>

          <p>The error:<br>ProxyError: (MaxRetryError("HTTPSConnectionPool(host=''huggingface.co'',
          port=443): Max retries exceeded with url: /openllmplayground/openalpaca_3b_600bt_preview/resolve/main/tokenizer.model
          (Caused by ProxyError(''Cannot connect to proxy.'', OSError(''Tunnel connection
          failed: 407 Proxy Authentication Required'')))"), ''(Request ID: 3e234643-e638-4824-836e-a1ded716b733)'')</p>

          <p>Does someone know how to solve it?</p>

          '
        raw: "Hello, I tried to import this model and got an error:\r\n\r\nmodel_path\
          \ = r'openllmplayground/openalpaca_3b_600bt_preview'\r\ntokenizer = LlamaTokenizer.from_pretrained(model_path)\r\
          \n\r\nThe error:\r\nProxyError: (MaxRetryError(\"HTTPSConnectionPool(host='huggingface.co',\
          \ port=443): Max retries exceeded with url: /openllmplayground/openalpaca_3b_600bt_preview/resolve/main/tokenizer.model\
          \ (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection\
          \ failed: 407 Proxy Authentication Required')))\"), '(Request ID: 3e234643-e638-4824-836e-a1ded716b733)')\r\
          \n\r\nDoes someone know how to solve it?"
        updatedAt: '2023-07-31T12:02:40.759Z'
      numEdits: 0
      reactions: []
    id: 64c7a2e04524c2aea7e654be
    type: comment
  author: VeronicaBatista
  content: "Hello, I tried to import this model and got an error:\r\n\r\nmodel_path\
    \ = r'openllmplayground/openalpaca_3b_600bt_preview'\r\ntokenizer = LlamaTokenizer.from_pretrained(model_path)\r\
    \n\r\nThe error:\r\nProxyError: (MaxRetryError(\"HTTPSConnectionPool(host='huggingface.co',\
    \ port=443): Max retries exceeded with url: /openllmplayground/openalpaca_3b_600bt_preview/resolve/main/tokenizer.model\
    \ (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection\
    \ failed: 407 Proxy Authentication Required')))\"), '(Request ID: 3e234643-e638-4824-836e-a1ded716b733)')\r\
    \n\r\nDoes someone know how to solve it?"
  created_at: 2023-07-31 11:02:40+00:00
  edited: false
  hidden: false
  id: 64c7a2e04524c2aea7e654be
  type: comment
is_pull_request: false
merge_commit_oid: null
num: 1
repo_id: openllmplayground/openalpaca_3b_600bt_preview
repo_type: model
status: open
target_branch: null
title: Error in  LlamaTokenizer.from_pretrained(
