!!python/object:huggingface_hub.community.DiscussionWithDetails
author: xia0o
conflicting_files: null
created_at: 2024-01-13 10:08:53+00:00
diff: null
endpoint: https://huggingface.co
events:
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: /avatars/d959df130075c6dfef4642bb4889750b.svg
      fullname: lanxia
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: xia0o
      type: user
    createdAt: '2024-01-13T10:08:53.000Z'
    data:
      edited: false
      editors:
      - xia0o
      hidden: false
      identifiedLanguage:
        language: en
        probability: 0.9180219173431396
      isReport: false
      latest:
        author:
          avatarUrl: /avatars/d959df130075c6dfef4642bb4889750b.svg
          fullname: lanxia
          isHf: false
          isPro: false
          name: xia0o
          type: user
        html: '<p>Both VAE cannot be used. After clicking to switch, it will automatically
          return to the one it was using</p>

          '
        raw: Both VAE cannot be used. After clicking to switch, it will automatically
          return to the one it was using
        updatedAt: '2024-01-13T10:08:53.752Z'
      numEdits: 0
      reactions: []
    id: 65a261354a68680500e8af15
    type: comment
  author: xia0o
  content: Both VAE cannot be used. After clicking to switch, it will automatically
    return to the one it was using
  created_at: 2024-01-13 10:08:53+00:00
  edited: false
  hidden: false
  id: 65a261354a68680500e8af15
  type: comment
is_pull_request: false
merge_commit_oid: null
num: 32
repo_id: dataautogpt3/OpenDalleV1.1
repo_type: model
status: open
target_branch: null
title: Why can't both VAE load when I use Web ui?
