!!python/object:huggingface_hub.community.DiscussionWithDetails
author: supriyo
conflicting_files: null
created_at: 2023-02-23 05:26:28+00:00
diff: null
endpoint: https://huggingface.co
events:
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: /avatars/e94e1efbeda6f20f2fe907f9c65db02b.svg
      fullname: Supriyo Roy Banerjee
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: supriyo
      type: user
    createdAt: '2023-02-23T05:26:28.000Z'
    data:
      edited: false
      editors:
      - supriyo
      hidden: false
      isReport: false
      latest:
        author:
          avatarUrl: /avatars/e94e1efbeda6f20f2fe907f9c65db02b.svg
          fullname: Supriyo Roy Banerjee
          isHf: false
          isPro: false
          name: supriyo
          type: user
        html: '<p>cannot import name ''_rng_spawn'' from ''scipy._lib._util'' </p>

          '
        raw: 'cannot import name ''_rng_spawn'' from ''scipy._lib._util'' '
        updatedAt: '2023-02-23T05:26:28.321Z'
      numEdits: 0
      reactions: []
    id: 63f6f904b4c9a104f4bcd08e
    type: comment
  author: supriyo
  content: 'cannot import name ''_rng_spawn'' from ''scipy._lib._util'' '
  created_at: 2023-02-23 05:26:28+00:00
  edited: false
  hidden: false
  id: 63f6f904b4c9a104f4bcd08e
  type: comment
is_pull_request: false
merge_commit_oid: null
num: 191
repo_id: CompVis/stable-diffusion-v1-4
repo_type: model
status: open
target_branch: null
title: error in colab while running from diffusers import StableDiffusionPipeline
