!!python/object:huggingface_hub.community.DiscussionWithDetails
author: ova1
conflicting_files: null
created_at: 2023-06-26 15:20:17+00:00
diff: null
endpoint: https://huggingface.co
events:
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: /avatars/5e321fd5edf074a6b27a8fee4d763508.svg
      fullname: Andrey
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: ova1
      type: user
    createdAt: '2023-06-26T16:20:17.000Z'
    data:
      edited: false
      editors:
      - ova1
      hidden: false
      identifiedLanguage:
        language: en
        probability: 0.8937587738037109
      isReport: false
      latest:
        author:
          avatarUrl: /avatars/5e321fd5edf074a6b27a8fee4d763508.svg
          fullname: Andrey
          isHf: false
          isPro: false
          name: ova1
          type: user
        html: '<p>Hey guys, any suggestions?</p>

          <p>Mac M1</p>

          <p>RuntimeError: Conv3D is not supported on MPS<br>Exception occurred: Conv3D
          is not supported on MPS</p>

          '
        raw: "Hey guys, any suggestions?\r\n\r\nMac M1\r\n\r\nRuntimeError: Conv3D\
          \ is not supported on MPS\r\nException occurred: Conv3D is not supported\
          \ on MPS\r\n\r\n\r\n"
        updatedAt: '2023-06-26T16:20:17.974Z'
      numEdits: 0
      reactions:
      - count: 1
        reaction: "\U0001F44D"
        users:
        - EricOder
    id: 6499bac11c50ecddbb3615c4
    type: comment
  author: ova1
  content: "Hey guys, any suggestions?\r\n\r\nMac M1\r\n\r\nRuntimeError: Conv3D is\
    \ not supported on MPS\r\nException occurred: Conv3D is not supported on MPS\r\
    \n\r\n\r\n"
  created_at: 2023-06-26 15:20:17+00:00
  edited: false
  hidden: false
  id: 6499bac11c50ecddbb3615c4
  type: comment
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: /avatars/8e9377ae7a8010d72cd193782ceb57c9.svg
      fullname: Matt Hoffner
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: true
      name: matthoffner
      type: user
    createdAt: '2023-07-01T16:57:59.000Z'
    data:
      edited: false
      editors:
      - matthoffner
      hidden: false
      identifiedLanguage:
        language: en
        probability: 0.7067687511444092
      isReport: false
      latest:
        author:
          avatarUrl: /avatars/8e9377ae7a8010d72cd193782ceb57c9.svg
          fullname: Matt Hoffner
          isHf: false
          isPro: true
          name: matthoffner
          type: user
        html: '<p>There is a PyTorch PR for this: <a rel="nofollow" href="https://github.com/pytorch/pytorch/pull/99246">https://github.com/pytorch/pytorch/pull/99246</a>
          </p>

          <p>You can try <code>PYTORCH_ENABLE_MPS_FALLBACK=1</code> to fallback to
          the CPU too.</p>

          '
        raw: "There is a PyTorch PR for this: https://github.com/pytorch/pytorch/pull/99246\
          \ \n\nYou can try `PYTORCH_ENABLE_MPS_FALLBACK=1` to fallback to the CPU\
          \ too."
        updatedAt: '2023-07-01T16:57:59.191Z'
      numEdits: 0
      reactions:
      - count: 1
        reaction: "\U0001F917"
        users:
        - ova1
    id: 64a05b179744fc9bc7f797f4
    type: comment
  author: matthoffner
  content: "There is a PyTorch PR for this: https://github.com/pytorch/pytorch/pull/99246\
    \ \n\nYou can try `PYTORCH_ENABLE_MPS_FALLBACK=1` to fallback to the CPU too."
  created_at: 2023-07-01 15:57:59+00:00
  edited: false
  hidden: false
  id: 64a05b179744fc9bc7f797f4
  type: comment
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: /avatars/aff36e43d4ba87b300004444b1eaf377.svg
      fullname: Yan
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: Jackieeeee
      type: user
    createdAt: '2023-09-21T07:36:23.000Z'
    data:
      edited: false
      editors:
      - Jackieeeee
      hidden: false
      identifiedLanguage:
        language: en
        probability: 0.7627605199813843
      isReport: false
      latest:
        author:
          avatarUrl: /avatars/aff36e43d4ba87b300004444b1eaf377.svg
          fullname: Yan
          isHf: false
          isPro: false
          name: Jackieeeee
          type: user
        html: '<p>After I set <code>PYTORCH_ENABLE_MPS_FALLBACK=1</code>,  I still
          got the error <code>RuntimeError: Conv3D is not supported on MPS</code></p>

          '
        raw: 'After I set `PYTORCH_ENABLE_MPS_FALLBACK=1`,  I still got the error
          `RuntimeError: Conv3D is not supported on MPS`'
        updatedAt: '2023-09-21T07:36:23.197Z'
      numEdits: 0
      reactions: []
    id: 650bf2772ec41a31f3216fbf
    type: comment
  author: Jackieeeee
  content: 'After I set `PYTORCH_ENABLE_MPS_FALLBACK=1`,  I still got the error `RuntimeError:
    Conv3D is not supported on MPS`'
  created_at: 2023-09-21 06:36:23+00:00
  edited: false
  hidden: false
  id: 650bf2772ec41a31f3216fbf
  type: comment
is_pull_request: false
merge_commit_oid: null
num: 7
repo_id: cerspense/zeroscope_v2_XL
repo_type: model
status: open
target_branch: null
title: 'RuntimeError: Conv3D is not supported on MPS'
