!!python/object:huggingface_hub.community.DiscussionWithDetails
author: nguyenmto
conflicting_files: null
created_at: 2022-11-30 17:36:45+00:00
diff: null
endpoint: https://huggingface.co
events:
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/1668596259536-noauth.png?w=200&h=200&f=face
      fullname: Nguyen Pham
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: nguyenmto
      type: user
    createdAt: '2022-11-30T17:36:45.000Z'
    data:
      edited: false
      editors:
      - nguyenmto
      hidden: false
      isReport: false
      latest:
        author:
          avatarUrl: https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/1668596259536-noauth.png?w=200&h=200&f=face
          fullname: Nguyen Pham
          isHf: false
          isPro: false
          name: nguyenmto
          type: user
        html: "<p>I am trying to setup stable-diffusion-2 with diffusers with revision\
          \ fp16 by the following code, but getting <code>RuntimeError: expected scalar\
          \ type Half but found Float</code></p>\n<pre><code>from diffusers import\
          \ StableDiffusionPipeline\npipe = StableDiffusionPipeline.from_pretrained(\"\
          stabilityai/stable-diffusion-2\",\n              revision=\"fp16\", \n \
          \             torch_dtype=torch.float16 )\npipe = pipe.to(\"cuda\")\nprompt\
          \ = \"a photo of an astronaut riding a horse on mars\"\nimage = pipe(prompt,\
          \ height=768, width=768).images[0]\nimage.save(\"astronaut_rides_horse.png\"\
          )\n</code></pre>\n<p>If I remove the <code>revision=\"fp16\",  torch_dtype=torch.float16</code>,\
          \ it works fine, does anyone know how to fix this ?</p>\n<p>Thank you</p>\n"
        raw: "I am trying to setup stable-diffusion-2 with diffusers with revision\
          \ fp16 by the following code, but getting `RuntimeError: expected scalar\
          \ type Half but found Float`\r\n\r\n```\r\nfrom diffusers import StableDiffusionPipeline\r\
          \npipe = StableDiffusionPipeline.from_pretrained(\"stabilityai/stable-diffusion-2\"\
          ,\r\n              revision=\"fp16\", \r\n              torch_dtype=torch.float16\
          \ )\r\npipe = pipe.to(\"cuda\")\r\nprompt = \"a photo of an astronaut riding\
          \ a horse on mars\"\r\nimage = pipe(prompt, height=768, width=768).images[0]\r\
          \nimage.save(\"astronaut_rides_horse.png\")\r\n```\r\n\r\nIf I remove the\
          \ `revision=\"fp16\",  torch_dtype=torch.float16`, it works fine, does anyone\
          \ know how to fix this ?\r\n\r\nThank you"
        updatedAt: '2022-11-30T17:36:45.621Z'
      numEdits: 0
      reactions: []
    id: 638794ad8b3c55fea3e446d9
    type: comment
  author: nguyenmto
  content: "I am trying to setup stable-diffusion-2 with diffusers with revision fp16\
    \ by the following code, but getting `RuntimeError: expected scalar type Half\
    \ but found Float`\r\n\r\n```\r\nfrom diffusers import StableDiffusionPipeline\r\
    \npipe = StableDiffusionPipeline.from_pretrained(\"stabilityai/stable-diffusion-2\"\
    ,\r\n              revision=\"fp16\", \r\n              torch_dtype=torch.float16\
    \ )\r\npipe = pipe.to(\"cuda\")\r\nprompt = \"a photo of an astronaut riding a\
    \ horse on mars\"\r\nimage = pipe(prompt, height=768, width=768).images[0]\r\n\
    image.save(\"astronaut_rides_horse.png\")\r\n```\r\n\r\nIf I remove the `revision=\"\
    fp16\",  torch_dtype=torch.float16`, it works fine, does anyone know how to fix\
    \ this ?\r\n\r\nThank you"
  created_at: 2022-11-30 17:36:45+00:00
  edited: false
  hidden: false
  id: 638794ad8b3c55fea3e446d9
  type: comment
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/1668596259536-noauth.png?w=200&h=200&f=face
      fullname: Nguyen Pham
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: nguyenmto
      type: user
    createdAt: '2022-11-30T18:00:37.000Z'
    data:
      edited: false
      editors:
      - nguyenmto
      hidden: false
      isReport: false
      latest:
        author:
          avatarUrl: https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/1668596259536-noauth.png?w=200&h=200&f=face
          fullname: Nguyen Pham
          isHf: false
          isPro: false
          name: nguyenmto
          type: user
        html: "<p>Full error attached</p>\n<pre><code>Traceback (most recent call\
          \ last):\n  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/flask/app.py\"\
          , line 2525, in wsgi_app\n    response = self.full_dispatch_request()\n\
          \  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/flask/app.py\"\
          , line 1822, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n\
          \  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/flask/app.py\"\
          , line 1820, in full_dispatch_request\n    rv = self.dispatch_request()\n\
          \  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/flask/app.py\"\
          , line 1796, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n\
          \  File \"main.py\", line 144, in index\n    id, image_list, total_generation_time,\
          \ seed = generate()\n  File \"main.py\", line 75, in generate\n    image_list\
          \ = generate_image(prompt, negative_prompt, width, height, samples, num_inference_steps,\
          \ guidance_scale, seed, id)\n  File \"main.py\", line 120, in generate_image\n\
          \    image = pipe(\n  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/autograd/grad_mode.py\"\
          , line 27, in decorate_context\n    return func(*args, **kwargs)\n  File\
          \ \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py\"\
          , line 518, in __call__\n    text_embeddings = self._encode_prompt(\n  File\
          \ \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py\"\
          , line 299, in _encode_prompt\n    text_embeddings = self.text_encoder(\n\
          \  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py\"\
          , line 1130, in _call_impl\n    return forward_call(*input, **kwargs)\n\
          \  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py\"\
          , line 722, in forward\n    return self.text_model(\n  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py\"\
          , line 1130, in _call_impl\n    return forward_call(*input, **kwargs)\n\
          \  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py\"\
          , line 643, in forward\n    encoder_outputs = self.encoder(\n  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py\"\
          , line 1130, in _call_impl\n    return forward_call(*input, **kwargs)\n\
          \  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py\"\
          , line 574, in forward\n    layer_outputs = encoder_layer(\n  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py\"\
          , line 1130, in _call_impl\n    return forward_call(*input, **kwargs)\n\
          \  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py\"\
          , line 317, in forward\n    hidden_states, attn_weights = self.self_attn(\n\
          \  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py\"\
          , line 1130, in _call_impl\n    return forward_call(*input, **kwargs)\n\
          \  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py\"\
          , line 257, in forward\n    attn_output = torch.bmm(attn_probs, value_states)\n\
          RuntimeError: expected scalar type Half but found Float\n</code></pre>\n"
        raw: "Full error attached\n```\nTraceback (most recent call last):\n  File\
          \ \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/flask/app.py\"\
          , line 2525, in wsgi_app\n    response = self.full_dispatch_request()\n\
          \  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/flask/app.py\"\
          , line 1822, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n\
          \  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/flask/app.py\"\
          , line 1820, in full_dispatch_request\n    rv = self.dispatch_request()\n\
          \  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/flask/app.py\"\
          , line 1796, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n\
          \  File \"main.py\", line 144, in index\n    id, image_list, total_generation_time,\
          \ seed = generate()\n  File \"main.py\", line 75, in generate\n    image_list\
          \ = generate_image(prompt, negative_prompt, width, height, samples, num_inference_steps,\
          \ guidance_scale, seed, id)\n  File \"main.py\", line 120, in generate_image\n\
          \    image = pipe(\n  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/autograd/grad_mode.py\"\
          , line 27, in decorate_context\n    return func(*args, **kwargs)\n  File\
          \ \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py\"\
          , line 518, in __call__\n    text_embeddings = self._encode_prompt(\n  File\
          \ \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py\"\
          , line 299, in _encode_prompt\n    text_embeddings = self.text_encoder(\n\
          \  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py\"\
          , line 1130, in _call_impl\n    return forward_call(*input, **kwargs)\n\
          \  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py\"\
          , line 722, in forward\n    return self.text_model(\n  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py\"\
          , line 1130, in _call_impl\n    return forward_call(*input, **kwargs)\n\
          \  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py\"\
          , line 643, in forward\n    encoder_outputs = self.encoder(\n  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py\"\
          , line 1130, in _call_impl\n    return forward_call(*input, **kwargs)\n\
          \  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py\"\
          , line 574, in forward\n    layer_outputs = encoder_layer(\n  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py\"\
          , line 1130, in _call_impl\n    return forward_call(*input, **kwargs)\n\
          \  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py\"\
          , line 317, in forward\n    hidden_states, attn_weights = self.self_attn(\n\
          \  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py\"\
          , line 1130, in _call_impl\n    return forward_call(*input, **kwargs)\n\
          \  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py\"\
          , line 257, in forward\n    attn_output = torch.bmm(attn_probs, value_states)\n\
          RuntimeError: expected scalar type Half but found Float\n```"
        updatedAt: '2022-11-30T18:00:37.965Z'
      numEdits: 0
      reactions: []
    id: 63879a4526952adc66edf20d
    type: comment
  author: nguyenmto
  content: "Full error attached\n```\nTraceback (most recent call last):\n  File \"\
    /home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/flask/app.py\", line\
    \ 2525, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/flask/app.py\"\
    , line 1822, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n\
    \  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/flask/app.py\"\
    , line 1820, in full_dispatch_request\n    rv = self.dispatch_request()\n  File\
    \ \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/flask/app.py\"\
    , line 1796, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n\
    \  File \"main.py\", line 144, in index\n    id, image_list, total_generation_time,\
    \ seed = generate()\n  File \"main.py\", line 75, in generate\n    image_list\
    \ = generate_image(prompt, negative_prompt, width, height, samples, num_inference_steps,\
    \ guidance_scale, seed, id)\n  File \"main.py\", line 120, in generate_image\n\
    \    image = pipe(\n  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/autograd/grad_mode.py\"\
    , line 27, in decorate_context\n    return func(*args, **kwargs)\n  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py\"\
    , line 518, in __call__\n    text_embeddings = self._encode_prompt(\n  File \"\
    /home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py\"\
    , line 299, in _encode_prompt\n    text_embeddings = self.text_encoder(\n  File\
    \ \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py\"\
    , line 1130, in _call_impl\n    return forward_call(*input, **kwargs)\n  File\
    \ \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py\"\
    , line 722, in forward\n    return self.text_model(\n  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py\"\
    , line 1130, in _call_impl\n    return forward_call(*input, **kwargs)\n  File\
    \ \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py\"\
    , line 643, in forward\n    encoder_outputs = self.encoder(\n  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py\"\
    , line 1130, in _call_impl\n    return forward_call(*input, **kwargs)\n  File\
    \ \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py\"\
    , line 574, in forward\n    layer_outputs = encoder_layer(\n  File \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py\"\
    , line 1130, in _call_impl\n    return forward_call(*input, **kwargs)\n  File\
    \ \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py\"\
    , line 317, in forward\n    hidden_states, attn_weights = self.self_attn(\n  File\
    \ \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py\"\
    , line 1130, in _call_impl\n    return forward_call(*input, **kwargs)\n  File\
    \ \"/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py\"\
    , line 257, in forward\n    attn_output = torch.bmm(attn_probs, value_states)\n\
    RuntimeError: expected scalar type Half but found Float\n```"
  created_at: 2022-11-30 18:00:37+00:00
  edited: false
  hidden: false
  id: 63879a4526952adc66edf20d
  type: comment
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/1584435275418-5dfcb1aada6d0311fd3d5448.jpeg?w=200&h=200&f=face
      fullname: Patrick von Platen
      isHf: true
      isOrgMember: true
      isOwner: false
      isPro: false
      name: patrickvonplaten
      type: user
    createdAt: '2022-12-07T13:48:01.000Z'
    data:
      edited: false
      editors:
      - patrickvonplaten
      hidden: false
      isReport: false
      latest:
        author:
          avatarUrl: https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/1584435275418-5dfcb1aada6d0311fd3d5448.jpeg?w=200&h=200&f=face
          fullname: Patrick von Platen
          isHf: true
          isPro: false
          name: patrickvonplaten
          type: user
        html: '<p>Hmm could you maybe open an issue for diffusers: <a rel="nofollow"
          href="https://github.com/huggingface/diffusers/issues/new/choose">https://github.com/huggingface/diffusers/issues/new/choose</a></p>

          '
        raw: 'Hmm could you maybe open an issue for diffusers: https://github.com/huggingface/diffusers/issues/new/choose'
        updatedAt: '2022-12-07T13:48:01.722Z'
      numEdits: 0
      reactions: []
    id: 63909991d2cf01fdfe349539
    type: comment
  author: patrickvonplaten
  content: 'Hmm could you maybe open an issue for diffusers: https://github.com/huggingface/diffusers/issues/new/choose'
  created_at: 2022-12-07 13:48:01+00:00
  edited: false
  hidden: false
  id: 63909991d2cf01fdfe349539
  type: comment
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/1668596259536-noauth.png?w=200&h=200&f=face
      fullname: Nguyen Pham
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: nguyenmto
      type: user
    createdAt: '2022-12-21T05:37:48.000Z'
    data:
      edited: false
      editors:
      - nguyenmto
      hidden: false
      isReport: false
      latest:
        author:
          avatarUrl: https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/1668596259536-noauth.png?w=200&h=200&f=face
          fullname: Nguyen Pham
          isHf: false
          isPro: false
          name: nguyenmto
          type: user
        html: '<p>Issue is resolved after upgrading transformers</p>

          '
        raw: Issue is resolved after upgrading transformers
        updatedAt: '2022-12-21T05:37:48.980Z'
      numEdits: 0
      reactions: []
      relatedEventId: 63a29bac931d2c13ad8dc978
    id: 63a29bac931d2c13ad8dc977
    type: comment
  author: nguyenmto
  content: Issue is resolved after upgrading transformers
  created_at: 2022-12-21 05:37:48+00:00
  edited: false
  hidden: false
  id: 63a29bac931d2c13ad8dc977
  type: comment
- !!python/object:huggingface_hub.community.DiscussionStatusChange
  _event:
    author:
      avatarUrl: https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/1668596259536-noauth.png?w=200&h=200&f=face
      fullname: Nguyen Pham
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: nguyenmto
      type: user
    createdAt: '2022-12-21T05:37:48.000Z'
    data:
      status: closed
    id: 63a29bac931d2c13ad8dc978
    type: status-change
  author: nguyenmto
  created_at: 2022-12-21 05:37:48+00:00
  id: 63a29bac931d2c13ad8dc978
  new_status: closed
  type: status-change
is_pull_request: false
merge_commit_oid: null
num: 24
repo_id: stabilityai/stable-diffusion-2
repo_type: model
status: closed
target_branch: null
title: 'revision=fp16 doesn''t work  (RuntimeError: expected scalar type Half but
  found Float)'
