!!python/object:huggingface_hub.community.DiscussionWithDetails
author: Artemis3196
conflicting_files: null
created_at: 2024-01-25 09:28:10+00:00
diff: null
endpoint: https://huggingface.co
events:
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: /avatars/56d702938a89db3a94b6a4bc45c071a4.svg
      fullname: Manas Tripathi
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: Artemis3196
      type: user
    createdAt: '2024-01-25T09:28:10.000Z'
    data:
      edited: false
      editors:
      - Artemis3196
      hidden: false
      identifiedLanguage:
        language: en
        probability: 0.560517430305481
      isReport: false
      latest:
        author:
          avatarUrl: /avatars/56d702938a89db3a94b6a4bc45c071a4.svg
          fullname: Manas Tripathi
          isHf: false
          isPro: false
          name: Artemis3196
          type: user
        html: '<p>I am following the repository :<a rel="nofollow" href="https://github.com/curiousily/Get-Things-Done-with-Prompt-Engineering-and-LangChain/blob/master/13.chat-with-multiple-pdfs-using-llama-2-and-langchain.ipynb">https://github.com/curiousily/Get-Things-Done-with-Prompt-Engineering-and-LangChain/blob/master/13.chat-with-multiple-pdfs-using-llama-2-and-langchain.ipynb</a></p>

          <p><a rel="nofollow" href="https://cdn-uploads.huggingface.co/production/uploads/65a8d719ef14f9e6038c8b19/1DplPx1bA8nKmG90625Eg.png"><img
          alt="image.png" src="https://cdn-uploads.huggingface.co/production/uploads/65a8d719ef14f9e6038c8b19/1DplPx1bA8nKmG90625Eg.png"></a><br>getting
          this error in the colab notebook</p>

          <p><a rel="nofollow" href="https://cdn-uploads.huggingface.co/production/uploads/65a8d719ef14f9e6038c8b19/aJxgBM4dDdukZ0yU_Gswy.png"><img
          alt="image.png" src="https://cdn-uploads.huggingface.co/production/uploads/65a8d719ef14f9e6038c8b19/aJxgBM4dDdukZ0yU_Gswy.png"></a></p>

          <p>Is it some error in setting the device: I am using a cpu.</p>

          '
        raw: "I am following the repository :https://github.com/curiousily/Get-Things-Done-with-Prompt-Engineering-and-LangChain/blob/master/13.chat-with-multiple-pdfs-using-llama-2-and-langchain.ipynb\r\
          \n\r\n![image.png](https://cdn-uploads.huggingface.co/production/uploads/65a8d719ef14f9e6038c8b19/1DplPx1bA8nKmG90625Eg.png)\r\
          \ngetting this error in the colab notebook\r\n\r\n![image.png](https://cdn-uploads.huggingface.co/production/uploads/65a8d719ef14f9e6038c8b19/aJxgBM4dDdukZ0yU_Gswy.png)\r\
          \n\r\nIs it some error in setting the device: I am using a cpu."
        updatedAt: '2024-01-25T09:28:10.863Z'
      numEdits: 0
      reactions: []
    id: 65b229aa2b3c9da0b497f0c9
    type: comment
  author: Artemis3196
  content: "I am following the repository :https://github.com/curiousily/Get-Things-Done-with-Prompt-Engineering-and-LangChain/blob/master/13.chat-with-multiple-pdfs-using-llama-2-and-langchain.ipynb\r\
    \n\r\n![image.png](https://cdn-uploads.huggingface.co/production/uploads/65a8d719ef14f9e6038c8b19/1DplPx1bA8nKmG90625Eg.png)\r\
    \ngetting this error in the colab notebook\r\n\r\n![image.png](https://cdn-uploads.huggingface.co/production/uploads/65a8d719ef14f9e6038c8b19/aJxgBM4dDdukZ0yU_Gswy.png)\r\
    \n\r\nIs it some error in setting the device: I am using a cpu."
  created_at: 2024-01-25 09:28:10+00:00
  edited: false
  hidden: false
  id: 65b229aa2b3c9da0b497f0c9
  type: comment
is_pull_request: false
merge_commit_oid: null
num: 29
repo_id: TheBloke/Llama-2-7B-Chat-GPTQ
repo_type: model
status: open
target_branch: null
title: 'Index out of range error: QAchain for pdf chatbot'
